<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.1 (Python 3.7.7 on linux)" generated="20200622 06:37:29.227" rpa="false">
<suite id="s1" name="myRobot" source="/home/mohammedathera/eclipse-workspace/myRobot">
<suite id="s1-s1" name="FirstTestSuite" source="/home/mohammedathera/eclipse-workspace/myRobot/FirstTestSuite.robot">
<test id="s1-s1-t1" name="Test1">
<kw name="Log" library="BuiltIn">
<doc>Logs the given message with the given level.</doc>
<arguments>
<arg>Testcase 1 is started</arg>
</arguments>
<msg timestamp="20200622 06:37:29.302" level="INFO">Testcase 1 is started</msg>
<status status="PASS" starttime="20200622 06:37:29.301" endtime="20200622 06:37:29.302"></status>
</kw>
<kw name="Open Application">
<arguments>
<arg>http://localhost:43981/wd/hub</arg>
<arg>automationName=UiAutomator2</arg>
<arg>deviceName=Pixel</arg>
<arg>udid=FA6A40301235</arg>
<arg>platformName=Android</arg>
<arg>appActivity=com.swaglabsmobileapp.SplashActivity</arg>
<arg>appPackage=com.swaglabsmobileapp</arg>
<arg>app=/home/mohammedathera/Downloads/Android.SauceLabs.Mobile.Sample.app.2.2.1.apk</arg>
</arguments>
<msg timestamp="20200622 06:37:29.304" level="FAIL">No keyword with name 'Open Application' found.</msg>
<status status="FAIL" starttime="20200622 06:37:29.303" endtime="20200622 06:37:29.304"></status>
</kw>
<doc>login with valid username and invalid password.</doc>
<status status="FAIL" starttime="20200622 06:37:29.300" endtime="20200622 06:37:29.304" critical="yes">No keyword with name 'Open Application' found.</status>
</test>
<status status="FAIL" starttime="20200622 06:37:29.293" endtime="20200622 06:37:29.304"></status>
</suite>
<status status="FAIL" starttime="20200622 06:37:29.274" endtime="20200622 06:37:29.305"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="myRobot">myRobot</stat>
<stat pass="0" fail="1" id="s1-s1" name="FirstTestSuite">myRobot.FirstTestSuite</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200622 06:37:29.298" level="ERROR">Error in file '/home/mohammedathera/eclipse-workspace/myRobot/FirstTestSuite.robot' on line 2: Importing test library 'AppiumLibrary' failed: ModuleNotFoundError: No module named 'decorator'
Traceback (most recent call last):
  File "/home/mohammedathera/.local/lib/python3.7/site-packages/AppiumLibrary/__init__.py", line 4, in &lt;module&gt;
    from AppiumLibrary.keywords import *
  File "/home/mohammedathera/.local/lib/python3.7/site-packages/AppiumLibrary/keywords/__init__.py", line 3, in &lt;module&gt;
    from ._logging import _LoggingKeywords
  File "/home/mohammedathera/.local/lib/python3.7/site-packages/AppiumLibrary/keywords/_logging.py", line 7, in &lt;module&gt;
    from .keywordgroup import KeywordGroup
  File "/home/mohammedathera/.local/lib/python3.7/site-packages/AppiumLibrary/keywords/keywordgroup.py", line 7, in &lt;module&gt;
    from decorator import decorator
PYTHONPATH:
  /home/mohammedathera/.local/lib/python3.7/site-packages
  /home/mohammedathera/eclipse-workspace/myRobot
  /usr/local/buildtools/current/sitecustomize
  /usr/lib/python37.zip
  /usr/lib/python3.7
  /usr/lib/python3.7/lib-dynload
  /home/mohammedathera/.local/lib/python3.7/site-packages
  /usr/local/lib/python3.7/dist-packages
  /usr/lib/python3/dist-packages</msg>
</errors>
</robot>
